Better safe than sorry.
Signed-off-by: Gabriel Linder <linder.gabriel@gmail.com>

diff --git a/.profile.d/vault b/.profile.d/vault
--- a/.profile.d/vault
+++ b/.profile.d/vault
@@ -29,7 +29,11 @@ kv_put() {
     IFS='#' read -r k f <<< "$1"
     v="$2"
     if ! vault kv patch -method=rw "$k" "$f"="$v"; then
-        echo 1>&2 "Patch failed, trying to put instead..."
-        vault kv put "$k" "$f"="$v"
+        if ! vault kv get "$k" >/dev/null 2>&1; then
+            echo 1>&2 "Patch failed, trying to put instead..."
+            vault kv put "$k" "$f"="$v"
+        else
+            echo 1>&2 "Patch failed, but secret exists: giving up"
+        fi
     fi
 }
